### ISSUE TITLE
State is not always Reactive!

### ISSUE THREAD

**Issue by hamzapurra** [meteor-space/template-controller#29]
Reactivity only works if you have defined a state object in the TemplateController and you are using {{state.counter}} in the template, for example. If you add a new a property to state using addProperty, say in onRendered, using {{state.newProp}} will not update. It's because Tracker fails to set up a Reactive dependency when it sees {{state.newProp}} as it's not defined yet.

**Comment by DominikGuzei** [comment]
@hamzapurra good observation! it only works when you do it before the Tracker computations are first accessing the state property of course 😉 this package cannot change this. So in your case try to move the state setup into `onCreated`, the helpers will not have been running by then and it should work.

**Comment by DominikGuzei** [comment]
I will update the docs to remove the part "at any point of the lifetime of your template" though ;)

**Comment by comerc** [comment]
It is bad :(

``` html
<template name="hello">
  <button>Click Me</button>
  <p>You've pressed the button {{state.counter}} times.</p>
</template>
```

``` javascript
  TemplateController('hello', {
    onRendered() {
      this.state.addProperty('counter', 123);
    },
    events: {
      'click button'() {
        // increment the counter when button is clicked
        this.state.counter++;
      }
    }
  });
```

**Comment by comerc** [comment]
How about hook, when rendered {{state.newProp}}?

If no state, then create it.

**Comment by DominikGuzei** [comment]
@comerc the problem here is that we cannot change the behavior of computations – if the reactive var is not defined at the point where it is accessed, no reactive dependency is registered. The only solution to this problem would be [ES6 Proxies](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Proxy) (dynamically create reactive vars if not exist) but these have no browser support at the moment and cannot be poly-filled.

**Comment by comerc** [comment]
How about [babel-plugin-proxy](https://github.com/krzkaczor/babel-plugin-proxy)?

**Comment by comerc** [comment]
[Is it solution?](https://github.com/dalgard/meteor-get-helper-reactively/)

**Comment by DominikGuzei** [comment]
@comerc no it breaks with the official Blaze api as stated in the readme. We don't need the use-case described by the author of view-model because we don't have a dynamic template "language" like he introduced to Blaze. Thus, it should be enough here to create the helpers in `onCreated` before the template is actually rendered. I don't see other big use-cases?

https://github.com/meteor/meteor/issues/5194
