### ISSUE TITLE
How to get current doc in list view when click event action?

### ISSUE THREAD

**Issue by thearabbit** [meteor-space/template-controller#31]
I use `reactive-table` to show list, and then I would to click `event action` to remove current doc.

![2016-05-12_13-53-37](https://cloud.githubusercontent.com/assets/4495160/15206440/661802cc-1849-11e6-857a-10805f9a5e46.png)

``` js
// Don't work
TemplateController('Core_branch', {
    events:{
        'click .js-update' (event, instance) {
            console.log(this);// can not get current doc
        },
   }
});
```

I tried 

``` js
// Work fine
Template.Core_branch.envents( {
        'click .js-update' (event, instance) {
            console.log(this);// can get current doc: {_id:..., name:.........}
        },
});
```

**Comment by DominikGuzei** [comment]
Hey @thearabbit!
`this` is always a reference to the template instance in event handlers (when using `TemplateController`) so you can just access the data context with `this.data`.

See Meteor documentation:
http://docs.meteor.com/#/full/template_data

**Comment by thearabbit** [comment]
It don' work

``` js
TemplateController('Core_branch', {
    events: {
        'click .js-update' (event, instance) {
            console.log(this.data);
        }
    }
});

// It show 
Object {}content: ()arguments: nullcaller: nulllength: 0name: ""prototype: Object__proto__: ()<function scope>__proto__: Object
```

Please help me.

**Comment by DominikGuzei** [comment]
@thearabbit this lib does not change the default logic / behavior of templating! `this.data` is either `null` (if no template data context) or the value you pass to it. Standard Meteor api

**Comment by DominikGuzei** [comment]
and btw. what you posted as "it show" looks really strange, i have no idea what this should be 😉

**Comment by thearabbit** [comment]
But when I tried with `Template......events({.....})` of Meteor standard via `this`, It is work fine.
(can get current doc in reactive-table row}

**Comment by DominikGuzei** [comment]
@thearabbit can you provide a full example that i can run? this will make it far easier for me to help you.

**Comment by thearabbit** [comment]
the first, thanks for your reply and helping.
This is my [testing repo](https://github.com/thearabbit/meteor-template-controller).

**Comment by DominikGuzei** [comment]
@thearabbit thanks for the repo, you can solve your problem like this:

```
events: {
  'click .js-remove'(event, instance) {
     const post = Blaze.getView(event.target).templateInstance();            
     Post.remove(post.data._id);
  },
}
```

**Comment by thearabbit** [comment]
Wow, It is complex.
Could you solve this to easy? 
(Like `Template of Meteor`, I can get via `this`)

**Comment by thearabbit** [comment]
Now I tried, it work fine.
Could you solve to easy for this?

**Comment by DominikGuzei** [comment]
@thearabbit no because your case is not the best practice, you are using a package that forces you to use the pattern of nested data contexts in event handlers which is evil. In this case you may have to do it like that (because the reactive-table package enforces bad practice), but i don't want to support this with a simple api.

**Comment by thearabbit** [comment]
Thanks again, Now I trie this it work fine.

``` js
Blaze.getData(event.target)
```

**Comment by DominikGuzei** [comment]
Ah perfect, thanks for the update @thearabbit – this looks quite decent indeed 😉 
I will add this to the package readme!

**Comment by DanielDornhardt** [comment]
I thought about this too / ran into this too - it's not working properly for me with `this.data` and Template.currentData() doesn't spit out anything useful either.

What about providing an additional parameter with the current context?

**Comment by DominikGuzei** [comment]
@DanielDornhardt did the solution of @thearabbit not work for you? And could you elaborate a bit more what exactly you need?

**Comment by DanielDornhardt** [comment]
Hi @DominikGuzei , the rabbits' solution works but isn't very "intuitive" - unless you know it that is.

So it'd be good to have it in the docs.

I might actually be slightly confused here and mixing template helpers and events - I am not sure whether you actually have the "this" context of the template instance for which the event handlers are registered in vanilla meteor... but I think you normally have, don't you?

And because in some cases this.data seems to be not properly up-to-date it'd be nice to have an alternative way "for dummies" to receive the current data context.

I thought that maybe an additional data parameter passed on to the event handler (so it becomer 'click .mything': function(event, data) ) may be nice (because we don't get the instance as a second parameter, why not pass the data in instead).

But I don't actually know what goes on under the hood and which data to supply actually, because inside of a template there can be multiple nested contexts from {{#each}}'s and so on, so I don't know actually how meteor handles that and so I am not sure how template-controller should handle that.

Maybe pass in a function as a second parameter that, when called, returns the result of Blaze.getData(event.target) :)

**Comment by DominikGuzei** [comment]
Hey @DanielDornhardt, i added an example for accessing the child template data context to the readme of the package 😉 

https://github.com/meteor-space/template-controller#accessing-the-data-context-of-child-templates

**Comment by DanielDornhardt** [comment]
Thanks, that's great! Love the package by the way, once more :)
